name: test-env-deploy
on:
  workflow_dispatch:
    inputs:
      version:
          description: 'The Version You Wanna Deploy To Test Env (First 6 Github SHA)'
          required: true
          default: "latest"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_VERSION: ${{ github.event.inputs.version }}
    steps:
    - uses: actions/checkout@v2
    - run: |
        echo "build"
        echo $GITHUB_VERSION
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: prod
    env:
      DEPLOY_ENV: prod
    steps:
    - run: echo $DEPLOY_ENV
