name: test-env-deploy
on:
  workflow_dispatch:
    inputs:
      version:
          description: 'The Version You Wanna Deploy To Test Env (First 6 Github SHA)'
          required: true
          default: "latest"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DEPLOY_ENV: test
      GITHUB_VERSION: ${{ github.event.inputs.version }}
    steps:
    - uses: actions/checkout@v2
    - run: ./.github/workflows/script.sh
