name: test-env-deploy
on:
  workflow_dispatch:
    inputs:
      version:
          description: 'The Version You Wanna Deploy To Test Env (First 6 Github SHA)'
          required: true
          default: "latest"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DEPLOY_ENV: test
      VERSION: ${{ github.event.inputs.version }}
    steps:
    - run: |
        echo "Version: ${{ env.VERSION }}"
        echo "ENV: ${{ env.DEPLOY_ENV }}" 
