  
name: consimer-bff-test-env-deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The Version You Wanna Deploy To Test Env'
        required: true
        default: ${{ github.sha:0:6 }}

jobs:
  Test-Deploy:
    runs-on: [ self-hosted,app ]

    steps:
      - run: |
        echo "Hello ${{ github.event.inputs.version }}!"
