# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
      version:
          description: 'The Version You Wanna Deploy To Test Env'
          required: true
          default: ${{ github.sha:0:6 }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
    - run: |
        echo "Log level: ${{ github.event.inputs.version }}"
        echo "Tags: ${{ github.event.inputs.tags }}" 
        echo "Tags: ${{ github.event.inputs.logLevel }}" 
