name: CI
on:
  workflow_dispatch:
    inputs:
      version:
          description: 'The Version You Wanna Deploy To Test Env'
          required: true
          default: "latest"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.version }}"
        echo "Tags: ${{ github.event.inputs.tags }}" 
        echo "Tags: ${{ github.event.inputs.logLevel }}" 
