#! /bin/bash
set -eux
ECR_ENDPOINT=436987280733.dkr.ecr.ap-southeast-1.amazonaws.com
PROJECT=consumer-bff
VERSION=$VERSION
RELEASE_IMAGE=${ECR_ENDPOINT}/${PROJECT}:${GITHUB_SHA:0:6}
RELEASE_IMAGE=${ECR_ENDPOINT}/${PROJECT}:${VERSION}

echo ECR_ENDPOINT
echo PROJECT
echo VERSION
echo RELEASE_IMAGE